Fix default group and dir-group for RHEL-derived linux config
sous-chefs/rsyslog pull request #153
Opened 2019-03-06 08:35 UTC by bish0polis

### Description

This change fixes the issue in #152 

### Issues Resolved

#152 

### Note

This patch is hereby public domain.   I committed without standing on the left foot, or including the right magic legal statement, or whatever voodoo is required; and I don't have the gear to prove adequate testing.   And after midnight the additional costs of donated labour start to become noticeable.  :-/

2019-09-17 14:03 UTC, caryp commented
@bish0polis thanks for the fix!  can you pls fix code style violations so this may be merged?

2020-11-20 19:45 UTC, Xorima commented
Closing due to inactivity. 

If this is still wanted please reopen or open another pull request. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

2020-11-22 06:24 UTC, bish0polis commented
It doesn't appear I can re-open it.

But if it sat for 20 months in a ready state, I don't know what re-opening's going to do.

2020-11-22 11:08 UTC, Xorima commented
Re-opening means there is still a desire for this feature, when we inherit cookbooks some older prs are no longer valid, this is a way of finding out features wanted/required vs features no longer wanted

2020-11-22 14:17 UTC, bish0polis commented
> Re-opening means there is still a desire for this feature

Neat.  I couldn't find the bit on the UI that allowed for re-opening.  Either I'm used to GL vs GH or an ACL prevented its inclusion.

2020-11-23 17:54 UTC, Xorima commented on CHANGELOG.md
> +
```suggestion
```

2020-11-23 18:00 UTC, Xorima requested changes

2020-11-23 18:00 UTC, Xorima commented on resources/file_input.rb
> +      group node['rsyslog']['group']
Hey @bish0polis 

Taking another look at this these would be much better as properties on the resource which default to these values for now.

Thanks

2023-09-28 01:47 UTC, xorima approved these changes

2023-09-28 01:56 UTC, xorima approved these changes

2026-07-10 21:24 UTC, closed without merging